version: '3.8'

services:
  usuarios:
    build: .
    container_name: usuarios_service
    command: ["python", "-m", "uvicorn", "users_app:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app

  pedidos:
    build: .
    container_name: pedidos_service
    command: ["python", "-m", "uvicorn", "pedidos_app:app", "--host", "0.0.0.0", "--port", "8002"]
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
